name: learn-github-actions
on:
  push:
    branches:
      - developp
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop
        uses: actions/checkout@v2
      - name: Checkout file system
        run: ls -al